source "https://api.berkshelf.com"

cookbook 'git'
cookbook 'vim'
cookbook 'emacs', '~> 0.10.0'
cookbook 'apache2'
cookbook 'apt'
cookbook 'mysql'
cookbook 'php'
cookbook 'database'
cookbook 'simple_iptables'
cookbook 'mysql2_chef_gem'
cookbook 'nrpe'
cookbook 'postfix'
cookbook 'poise-python', '~> 1.6.0'
